---
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started
    - name: Create default nginx site-available
      copy: src=default dest=/etc/nginx/sites-available/
      notify:
        - 'Restart nginx'
    - name: Create default nginx site-enabled
      copy: src=default dest=/etc/nginx/sites-enabled/
    - name: Enable nginx to start on reboot
      command: systemctl enable nginx
    - name: Change file permissions - sites-available
      file:
        path: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: '0644'
